-- Galileo shared KPI comments (read and written by comments_store.py).
-- Run once as a user who can create tables in `sbx-logistics`.gli_nexus, then
-- grant the GLI Nexus app service principal read and write access.
-- The table name can be overridden with GALILEO_COMMENTS_TABLE.

CREATE TABLE IF NOT EXISTS `sbx-logistics`.gli_nexus.galileo_comments (
  id           STRING    NOT NULL COMMENT 'uuid4 hex, generated by the app',
  flow         STRING    NOT NULL COMMENT 'Content row key: Category|Sub-category',
  market       STRING    NOT NULL COMMENT 'REP or LM',
  area         STRING    NOT NULL COMMENT 'ALL, EMEA, NA, APAC or LATAM',
  author_email STRING    NOT NULL COMMENT 'X-Forwarded-Email of the author',
  text         STRING    NOT NULL,
  created_at   TIMESTAMP NOT NULL
)
COMMENT 'Galileo Observatory: shared comments on Content KPIs';

-- Replace <app-service-principal> with the GLI Nexus app's service principal
-- (application id or display name, as shown in the app's settings).
GRANT SELECT, MODIFY ON TABLE `sbx-logistics`.gli_nexus.galileo_comments
  TO `<app-service-principal>`;
